/* Main.c file generated by New Project wizard
 *
 * Created:   ?? 5? 11 2025
 * Processor: AT89C52
 * ComPiler:  Keil for 8051
 */
#include <reg51.h>
#include <stdio.h>
  
// 毫秒级延时函数
void delay_ms(unsigned int ms)
{
    unsigned int i, j;
    for (i = 0; i < ms; i++)
        for (j = 0; j < 120; j++);
}
  
unsigned char a;
  
// 主函数，控制P2端口输出，通过P3端口输入控制
void main(void)
{
    P2 = ~0x01;   // 初始化P2端口，设置初始状态
    while (1)
    {
        if ((P3 & 0x02) == 0) // 判断P3.1引脚电平
        {
            delay_ms(50); // 延时消抖
            if ((P3 & 0x02) == 0) // 再次判断确认按键按下
            {
                while ((P3 & 0x02) == 0); // 等待按键释放
                delay_ms(50); // 延时消抖
                a++;
                if (a >= 8)
                    a = 0;
                P2 = ~(0x01 << a);
            }
        }
  
        if ((P3 & 0x01) == 0) // 判断P3.0引脚电平
        {
            delay_ms(50); // 延时消抖
            if ((P3 & 0x01) == 0) // 再次判断确认按键按下
            {
                while ((P3 & 0x01) == 0); // 等待按键释放
                delay_ms(50); // 延时消抖
                if (a == 0)
                    a = 7;
                else
                    a--;
                P2 = ~(0x01 << a);
            }
        }
    }
}