/* Main.c file generated by New Project wizard
 *
 * Created:   周日 5月 11 2025
 * Processor: AT89C52
 * ComPiler:  Keil for 8051
 */
#include <reg51.h>
#include <stdio.h>
 
// 延时函数，单位为毫秒
void delay_ms(unsigned int ms)
{
    unsigned int i, j;
    for (i = 0; i < ms; i++)
        for (j = 0; j < 120; j++);
}
 
unsigned char a;
 
// 主函数，程序入口
void main(void)
{
    P0 = ~0x01;   // 低电平有效，亮第一个灯
    while (1)
    {
        if ((P1 & 0x02) == 0) // 检测P1.1按键
        {
            delay_ms(50); // 延时去抖动
            if ((P1 & 0x02) == 0) // 再次确认按键是否按下
            {
                while ((P1 & 0x02) == 0); // 等待按键释放
                delay_ms(50); // 再次延时去抖动
                a++;
                if (a >= 8)
                    a = 0;
                P0 = ~(0x01 << a);
            }
        }
 
        if ((P1 & 0x01) == 0) // 检测P1.0按键
        {
            delay_ms(50); // 延时去抖动
            if ((P1 & 0x01) == 0) // 再次确认按键是否按下
            {
                while ((P1 & 0x01) == 0); // 等待按键释放
                delay_ms(50); // 再次延时去抖动
                if (a == 0)
                    a = 7;
                else
                    a--;
                P0 = ~(0x01 << a);
            }
        }
    }
}